# Generated by Django 5.2.4 on 2025-07-12 09:27

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_tag_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='tags',
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.CharField(blank=True, max_length=50, verbose_name=core.models.Tag),
        ),
    ]
